version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: image/Dockerfile
    ports:
      - "22512:56242"
    volumes:
      - .:/app
    networks:
      - app-network
    command: ["python3", "main.py"]

networks:
    app-network:
        driver: bridge